sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache

git:
  depth: false
  
install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 -y
  - travis_retry sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev -y
  - travis_retry sudo apt-get install software-properties-common -y
  - travis_retry sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
  - travis_retry sudo apt-get install libminiupnpc-dev -y
  - travis_retry sudo apt-get install libzmq3-dev -y
  - travis_retry sudo apt-get install libqt4-dev libprotobuf-dev protobuf-compiler -y
  - travis_retry sudo apt-get install libqrencode-dev -y
  - travis_retry sudo apt-get install git -y
  - travis_retry sudo apt-get install ca-certificates -y

script: 
  - ./autogen.sh
  - ./configure --enable-tests 
  - make           
  - cd src
  - mkdir unittestresults
  - ./yacoin_test > ./unittestresults/unittestresults.txt
