name: Yacoin multi platform build

on: [push]

jobs:
  build-ubuntu-1604:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTION
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_SHA
          docker pull dev34253/yacoin-build:ubuntu.16.04
          docker run -v /home/runner/work/yacoin/yacoin:/src -e BUILDVERSION=$GITHUB_RUN_NUMBER dev34253/yacoin-build:ubuntu.16.04
      - uses: actions/upload-artifact@v1
        with:
          name: yacoind-ubuntu-16.04
          path: /home/runner/work/yacoin/yacoin/release/yacoind
      - uses: actions/upload-artifact@v1
        with:
          name: yacoin-qt-ubuntu-16.04
          path: /home/runner/work/yacoin/yacoin/release/yacoin-qt
  build-ubuntu-1604-low-difficulty:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker pull dev34253/yacoin-build:ubuntu.16.04
          docker run -v /home/runner/work/yacoin/yacoin:/src --entrypoint /bin/bash dev34253/yacoin-build:ubuntu.16.04 -c "cd /src && ./autogen.sh && ./configure --with-gui=no --enable-low-difficulty-for-development && make"
          docker run -v /home/runner/work/yacoin/yacoin:/src --entrypoint /src/test/functional/test_runner.py dev34253/yacoin-build:ubuntu.16.04 -j 1
      - uses: actions/upload-artifact@v1
        with:
          name: yacoind-low-difficulty-16.04
          path: /home/runner/work/yacoin/yacoin/src/yacoind
  build-ubuntu-1804:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker pull dev34253/yacoin-build:ubuntu.18.04
          docker run -v /home/runner/work/yacoin/yacoin:/src -e BUILDVERSION=$GITHUB_RUN_NUMBER dev34253/yacoin-build:ubuntu.18.04
      - uses: actions/upload-artifact@v1
        with:
          name: yacoind-ubuntu-18.04
          path: /home/runner/work/yacoin/yacoin/release/yacoind
      - uses: actions/upload-artifact@v1
        with:
          name: yacoin-qt-ubuntu-18.04
          path: /home/runner/work/yacoin/yacoin/release/yacoin-qt
  build-windows:
    runs-on: windows-latest  
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker pull dev34253/yacoin-build:windows.latest
          docker run -v %CD%:c:\git\src -e BUILDVERSION=$GITHUB_RUN_NUMBER dev34253/yacoin-build:windows.latest
        shell: cmd
      - uses: actions/upload-artifact@v1
        with:
          name: yacoin-qt-windows
          path: release/yacoin-qt.exe
      - uses: actions/upload-artifact@v1
        with:
          name: yacoind-windows
          path: src/yacoind.exe
    